config/routes.rb
GikTuts::Application.routes.draw do
  get "signup", to: "gik_users#new"
  match "signin", to: "gik_users#signin", via: [:post, :get]
  match "signout", to: "gik_users#signout", via: [:post, :get]
  get "gik_users/create"
  match "edit", to: "gik_users#edit", via: [:get, :patch]
  get "profile", to: "gik_users#profile"
  resources :gik_users

  root 'home#index'
  match'contact', to: 'home#contact', via: [:get, :post]
  match'service', to: 'home#profile', via: [:get, :post]
  get 'library', to: 'home#profile'
  match 'google', to: 'home#google', via: [:get, :post]
  match 'map', to: 'google_maps#index', via: [:get, :post]

end

app/models/gik_user.rb
class GikUser < ActiveRecord::Base
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, presence: true
  validates :password_confirmation, length: { minimum: 6 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gik_users_controller.rb
class GikUsersController < ApplicationController
  layout "layout_index"
  include ApplicationHelper

  def new
    @gik_user = GikUser.new
  end

  def create
    @gik_user = GikUser.new(gik_user_params)
    if @gik_user.valid?
      begin
        @gik_user.save
      rescue
      end
      redirect_to root_path
    else
      render 'new'
    end
  end

  # method edit profile user
  def edit
    return redirect_to root_path unless current_user
    unless params[:gik_user].blank?
      @gik_user = GikUser.where(email: params[:gik_user][:email].downcase).first
      # @gik_user.attributes = params['gik_user']
      @gik_user.name = params['gik_user']['name']
      @gik_user.email = params['gik_user']['email']
      @gik_user.password = params['gik_user']['password']
      @gik_user.password_confirmation = params['gik_user']['password_confirmation']

      if @gik_user.valid?
        begin
          @gik_user.save
          session['gik_user'] = @gik_user
        rescue
        end
        redirect_to root_path
      else
        return render 'edit'
      end
    else
      @gik_user = current_user
      render 'edit'
    end
  end

  # method see profile of user
  def profile
  end

  # method sign in user
  def signin
    return render 'signin' if params[:gik_user].blank?
    gik_user = GikUser.where(email: params[:gik_user][:email].downcase).first

    if gik_user && gik_user.authenticate(params[:gik_user][:password])
      create_session(gik_user)
      redirect_to root_path
    else
      render 'signin'
    end
  end

  # method signout user
  def signout
    destroy_session
    redirect_to root_path
  end

  private
  # strong parameters signup user
  def gik_user_params
    params.require(:gik_user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/google_maps_controller.rb
class GoogleMapsController < ApplicationController
  layout 'google_bus'
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "layout_index"
  def index

  end

  def contact
  end

  def profile
  end

  def google
    return render  layout: 'google_map'
  end

  def google_map
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "gikTuts"
    if page_title.blank?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def create_session(gik_user)
    session[:gik_user] = gik_user
  end

  def current_user
    session[:gik_user]
  end

  def destroy_session
    session.delete(:gik_user)
  end

  def errors_form(model, field_names)
    # get all errors of forms
    errors = model.errors.messages

    errors_message = ''
    field_names.each do |field_name|
      if errors.keys.include?(field_name) && !errors[field_name].empty?
        errors_message << errors[field_name][0] << "<br />"
      end
    end

    unless errors_message.empty?
      return "<div id='display-error'>#{errors_message}</div>".html_safe   #errors_message.html_safe
    end
    return errors_message
  end

end

app/helpers/gik_users_helper.rb
module GikUsersHelper
end

app/helpers/google_maps_helper.rb
module GoogleMapsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gik_users/edit.html.erb
<%= provide(:title, "Cập nhật tài khoản") %>

<div class="wrapper">
  <%= form_for @gik_user, :url => url_for(controller: "gik_users", action: "edit"), html: { class: 'form1' } do |f| %>
    <div class="formtitle">Cập nhật tài khoản</div>
    <div class="input">
      <div class="inputtext">Họ và tên: </div>
      <div class="inputcontent">
        <%= errors_form(@gik_user, [:name]) %>
        <%= f.text_field :name, placeholder: 'Họ và tên' %>
      </div>
    </div>
    <div class="input">
      <div class="inputtext">Email: </div>
      <div class="inputcontent">
        <%= errors_form(@gik_user, [:email]) %>
        <%= f.text_field :email, placeholder: 'Email' %>
      </div>
    </div>
    <div class="input nobottomborder">
      <div class="inputtext">Mật khẩu: </div>
      <div class="inputcontent">
        <%= errors_form(@gik_user, [:password]) %>
        <%= f.password_field :password, placeholder: 'Mật khẩu' %>
      </div>
    </div>
    <div class="input nobottomborder">
      <div class="inputtext">Gõ lại mật khẩu: </div>
      <div class="inputcontent">
        <%= errors_form(@gik_user, [:password_confirmation]) %>
        <%= f.password_field :password_confirmation, placeholder: 'Gõ lại mật khẩu' %>
        <br/><%= link_to "Đã có tài khoản?", signin_path %>
      </div>
    </div>
    <div class="buttons">
      <%= f.submit "Cập nhật", class: 'orangebutton' %>
      <%= f.submit "Huỷ bỏ", class: 'greybutton' %>
    </div>
  <% end %>
</div>

app/views/gik_users/new.html.erb
<%= provide(:title, "Đăng ký") %>

<div class="wrapper">
  <%= form_for @gik_user, html: { class: 'form1' } do |f| %>
    <div class="formtitle">Đăng ký tài khoản</div>
    <div class="input">
      <div class="inputtext">Họ và tên: </div>
      <div class="inputcontent">
        <%= errors_form(@gik_user, [:name]) %>
        <%= f.text_field :name, placeholder: 'Họ và tên' %>
      </div>
    </div>
    <div class="input">
      <div class="inputtext">Email: </div>
      <div class="inputcontent">
        <%= errors_form(@gik_user, [:email]) %>
        <%= f.text_field :email, placeholder: 'Email' %>
      </div>
    </div>
    <div class="input nobottomborder">
      <div class="inputtext">Mật khẩu: </div>
      <div class="inputcontent">
        <%= errors_form(@gik_user, [:password]) %>
        <%= f.password_field :password, placeholder: 'Mật khẩu' %>
      </div>
    </div>
    <div class="input nobottomborder">
      <div class="inputtext">Gõ lại mật khẩu: </div>
      <div class="inputcontent">
        <%= errors_form(@gik_user, [:password_confirmation]) %>
        <%= f.password_field :password_confirmation, placeholder: 'Gõ lại mật khẩu' %>
        <br/><%= link_to "Đã có tài khoản?", signin_path %>
      </div>
    </div>
    <div class="buttons">
      <%= f.submit "Đăng ký", class: 'orangebutton' %>
      <%= f.submit "Huỷ bỏ", class: 'greybutton' %>
    </div>
  <% end %>
</div>

app/views/gik_users/signin.html.erb
<%= provide(:title, "Đăng nhập") %>

<div class="wrapper">
  <%= form_tag({controller: 'gik_users', action: 'signin'}, method: "post", class: 'form1') do %>
    <div class="formtitle">Đăng nhập</div>
    <div class="input">
      <div class="inputtext">Email: </div>
      <div class="inputcontent">
        <%= text_field_tag "gik_user[email]", nil, placeholder: 'Email' %>
      </div>
    </div>
    <div class="input nobottomborder">
      <div class="inputtext">Mật khẩu: </div>
      <div class="inputcontent">
        <%= password_field_tag "gik_user[password]", nil, placeholder: 'Mật khẩu' %>
        <br/><%= link_to "Quên mật khẩu?", "#" %><span><%= link_to "Chưa đăng ký?", signup_path %></span>
      </div>
    </div>
    <div class="buttons">
      <%= submit_tag "Đăng nhập", class: 'orangebutton' %>
      <%= submit_tag "Huỷ bỏ", class: 'greybutton' %>
    </div>
  <% end %>
</div>

app/views/google_maps/index.html.erb
<% provide(:title, "Bản đồ") %>

app/views/home/contact.html.erb
<% provide(:title, "Liên hệ") %>
<div id="main_content">
  <div id="contact_area">
    <div class="container">
      <h2 id="contact">Liên hệ trực tiếp</h2>
      <div id="contact_info">
        <div id="contact_info_left">
          <p>Cám ơn bạn đã tham quan website, nếu có bất kỳ thắc mắc nào, vui lòng liên hệ trực tiếp với chúng tôi qua số điện thoại hay địa chỉ bên duới.
          <br />
          <br />
          Hoặc bạn có thể phản hồi qua hộp thư mail bên duới: <a href="mailto:phamkhanh90@gmail.com" class="bold_text blue_text">phamkhanh90@gmail.com</a></p>
          <form action="#" method="post" id="contact_form">
            <fieldset>
              <ol>
                <li>
                  <label for="name">Tên của bạn</label><input type="text" name="name" value="" size="77" maxlength="" id="name" />
                </li>
                <li>
                  <label for="email">Địa chỉ email</label><input type="text" name="email" value="" size="77" maxlength="" id="email" />
                </li>
                <li>
                  <label for="email">Tiêu đề</label><input type="text" name="email" value="" size="77" maxlength="" id="subject" />
                </li>
                <li>
                  <label for="message">Nội dung liên hệ</label><textarea name="message" rows="10" cols="59" id="message"></textarea>
                </li>
                <li>
                  <input type="submit" value="SUBMIT" size="" maxlength="" />
                </li>
              </ol>
            </fieldset>
          </form>
        </div> <!-- END #contact_info_left -->
        <div id="contact_info_right">
          <div id="address">
            <h3>Địa Chỉ Chính</h3>
            <p><span class="bold_text"></span>
            • Địa chỉ: P601, Tầng 6, Tòa nhà EliNext
            <br>
             413/36 QL 50, P5, Q. 8, TP.HCM
            <br>
            • Điện thoại: (+84) 0121 7698 526
            <br>
            • Fax: (08) 3995 3428
            <br>
            • Email: phamkhanh90@gmail.com</p>
          </div> <!-- END #address -->
        </div> <!-- END #contact_info_right -->
      </div> <!-- END #contact_info -->
    </div> <!-- END .container -->
  </div> <!-- END #contact_area -->
</div> <!-- END #main_content -->
<iframe src="google.htm" width="820px" height="720px" frameborder="0"></iframe>

app/views/home/index.html.erb
<% provide(:title, "Trang chủ") %>
<div id="main_content">
  <div id="slideshow_area">
    <div class="container">
      <div id="slideshow_container">
        <ul>
          <li><%= image_tag("component/banner_image.jpg", alt: "banner1")%></li>
        </ul>
        <div id="slideshow_pagination">
          <ul>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
            <li><a href="#" class="current"></a></li>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
          </ul>
        </div> <!-- END #slideshow_pagination -->
      </div> <!-- END #slideshow_container -->
    </div> <!-- END .container -->
  </div> <!-- END #slideshow_area -->
  <div id="mid_content">
    <div class="container">
      <div class="mid_content_info mid_content_space">
        <h2 id="clean">CLEAN THEME</h2>
        <p>Ut nec lorem id orci convallis porta. Donec pharetra neque eu velit dictum molestie. Duis porta gravida augue sed viverra. Quisque at nulla leo,
        non aliquet mi.</p>
        <a href="#"><%= image_tag("component/arrow_right.png", alt: "arrow right")%>Read More</a>
      </div>
      <div class="mid_content_info mid_content_space">
        <h2 id="responsive">RESPONSIVE DESIGN</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod placerat dui et tincidunt. Sed sollicitudin posuere auctor. Phasellus at
        ultricies nisl. Integer at leo eros.</p>
        <a href="#"><%= image_tag("component/arrow_right.png", alt: "arrow right")%>Read More</a>
      </div>
      <div class="mid_content_info mid_content_space">
        <h2 id="fully">FULLY LAYERED PSD</h2>
        <p>Phasellus lobortis metus non augue sodales volutpat. Vestibulum sit amet nibh eros, hendrerit venenatis est. In vitae nulla nec purus cursus
        pretium sed id magna.</p>
        <a href="#"><%= image_tag("component/arrow_right.png", alt: "arrow right")%>Read More</a>
      </div>
      <div class="mid_content_info">
        <h2 id="ready">READY FOR CODING</h2>
        <p>Vivamus convallis feugiat mauris sed posuere. Nam rutrum, quam quis euismod commodo, elit est porta quam, non placerat eros neque porta ante.
        Fusce quis odio urna.</p>
        <a href="#"><%= image_tag("component/arrow_right.png", alt: "arrow right")%>Read More</a>
      </div>
    </div> <!-- END .container -->
  </div> <!-- END #mid_content -->
  <div id="latest_works">
    <h3>NHỮNG VIDEO ĐUỢC XEM NHIỀU NHẤT</h3>
    <div id="carousel_nav">
      <a href="#"><%= image_tag("component/bluearrow_left.png", alt: "arrow left")%></a>
      <a href="#"><%= image_tag("component/bluearrow_right.png", alt: "arrow right")%></a>
    </div> <!-- END #carousel_nav -->
    <div id="carousel_wrapper">
      <ul>
        <li id="work01">
          <a href="#"><%= image_tag("component/sample_view.gif", alt: "work01")%></a>
        </li>
        <li id="work02">
          <a href="#"><%= image_tag("component/sample_view.gif", alt: "work02")%></a>
        </li>
        <li id="work03">
          <a href="#"><%= image_tag("component/sample_view.gif", alt: "work03")%></a>
        </li>
        <li id="work04">
          <a href="#"><%= image_tag("component/sample_view.gif", alt: "work04")%></a>
        </li>
      </ul>
    </div> <!-- END #carousel_wrapper -->
  </div> <!-- END #latest_works -->
  <div id="bottom_content">
    <div id="testimonials">
      <h3>TESTIMONIALS</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut nulla sapien, at aliquam erat. Sed vitae massa tellus. Aliquam commodo
      aliquam metus, sed iaculis nibh tempus id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci
      luctus et ultrices posuere cubilia Curae; Etiam nec nisi in nisl euismod fringilla.
      <br />
      <br />
      <span class="testimonial_name">John Travis, CEO, DomainName.com</span></p>
    </div> <!-- END #testimonials -->
    <div id="clients">
      <h3>OUR CLIENTS</h3>
      <ul>
        <li><%= image_tag("component/client01.jpg", alt: "Cox Communications")%></li>
        <li><%= image_tag("component/client02.jpg", alt: "CNN")%></li>
        <li><%= image_tag("component/client03.jpg", alt: "Apartment Finder")%></li>
        <li><%= image_tag("component/client04.jpg", alt: "John Deere")%></li>
        <li><%= image_tag("component/client05.jpg", alt: "Banana Boat")%></li>
        <li><%= image_tag("component/client06.jpg", alt: "Fuji Film")%></li>
      </ul>
    </div> <!-- END #clients -->
  </div> <!-- END #bottom_content -->
  <div id="download">
    <p>This is a clean and modern, four column website PSD template. You can code it into a Wordpress website, HTML5 responsive website for your personal
    or client works. So ahead and download this wonderful PSD template!</p>
    <a href="#">DOWNLOAD PSD</a>
  </div> <!-- END #download -->
</div> <!-- END #main_content -->

app/views/home/profile.html.erb
<h1>Home#profile</h1>
<p>Find me in app/views/home/profile.html.erb</p>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <div id="footer_about" class="footer_info">
      <h4>about us</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod placerat dui et tincidunt. Sed sollicitudin posuere auctor. Phasellus at
      ultricies nisl. Integer at leo eros. Ut nec lorem id orci convallis porta. Donec pharetra neque eu velit dictum molestie. </p>\
    </div> <!-- END #footer_about -->
    <div id="footer_explore" class="footer_info">
      <h4>explore</h4>
      <ul>
        <li><a href="index.html">home</a></li>
        <li><a href="#">about us</a></li>
        <li><a href="#">services</a></li>
        <li><a href="portfolio.html">portfolio</a></li>
        <li><a href="#">blog</a></li>
      </ul>
    </div> <!-- END #footer_about -->
    <div id="footer_browse" class="footer_info">
      <h4>browse</h4>
      <ul>
        <li><a href="#">careers</a></li>
        <li><a href="#">press &amp; media</a></li>
        <li><a href="contact.html">contact us</a></li>
        <li><a href="#">terms of service</a></li>
        <li><a href="#">privacy policy</a></li>
      </ul>
    </div> <!-- END #footer_about -->
    <div id="footer_contact" class="footer_info">
      <h4>contact us</h4>
      <p><span class="bold_text">BisLite Inc.</span>
      <br />
      Always Street 265
      <br />
      0X - 125 - Vietnam
      <br />
      <br />
      Phone: 012-1769-8526
      <br />
      Fax: 987-6543-210</p>
    </div> <!-- END #footer_about -->
    <div id="footer_connect" class="footer_info">
      <h4>connect with us</h4>
      <ul>
        <li><a href="#" id="facebook" title="Facebook">Facebook</a></li>
        <li><a href="#" id="dribbble" title="Dribbble">Dribbble</a></li>
        <li><a href="#" id="pinterest" title="Pinterest">Pinterest</a></li>
        <li><a href="#" id="linkedin" title="LinkedIn">LinkedIn</a></li>
        <li><a href="#" id="skype" title="Skype">Skype</a></li>
        <li><a href="#" id="sharethis" title="Share This">ShareThis</a></li>
      </ul>
    </div> <!-- END #footer_about -->
    <p id="copyright">&copy; Copyright 2013 gikTuts.net, All rights reserved
    <br />
    ® gikTuts giữ bản quyền nội dung trên website này.</p>
    <a href="index.html" id="footer_logo">BisLite</a>
  </div> <!-- END .container -->
</div> <!-- END #footer -->

app/views/layouts/_header.html.erb
<div id="header">
  <div class="container">
    <h1><a href="/">gikTuts</a></h1>
    <div id="main_menu">
      <ul>
        <li class="first_list"><%= link_to "Trang chủ", root_path, class: 'main_menu_first' %></li>
        <li class="first_list"><%= link_to "Bản Đồ", map_path, class: "main_menu_first" %></li>
        <li class="first_list with_dropdown"><%= link_to "Thư Viện Ebook", '#', class: 'main_menu_first' %>
          <ul>
            <li class="second_list second_list_border"><%= link_to "Java", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "Ruby on Rails", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "MongoDB", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "MySQL", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "Oracle", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "Linux", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "PHP", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to ".NET", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "C/C++", '#', class: 'main_menu_second' %></li>
            <li class="second_list"><%= link_to "Groovy on Grails", '#', class: 'main_menu_second' %></li>
          </ul>
        </li>
        <li class="first_list with_dropdown"><a href="portfolio.html" class="main_menu_first">Thư Viện Video</a>
          <ul>
            <li class="second_list second_list_border"><%= link_to "Java", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "Ruby on Rails", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "MongoDB", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "MySQL", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "Oracle", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "Linux", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "PHP", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to ".NET", '#', class: 'main_menu_second' %></li>
            <li class="second_list second_list_border"><%= link_to "C/C++", '#', class: 'main_menu_second' %></li>
            <li class="second_list"><%= link_to "Groovy on Grails", '#', class: 'main_menu_second' %></li>
          </ul>
        </li>
        <li class="first_list"><%= link_to "Hỗ Trợ", contact_path, class: "main_menu_first" %></li>
        <% if current_user.blank? %>
          <li class="first_list"><%= link_to "Đăng Nhập", signin_path, class: 'main_menu_first', id: "id_signup" %></li>
        <% else %>
          <li class="first_list with_dropdown"><%= link_to "Cài Đặt", "#", class: 'main_menu_first' %>
            <ul>
              <li class="second_list second_list_border"><%= link_to "Thông tin tài khoản", '#', class: 'main_menu_second' %></li>
              <li class="second_list second_list_border"><%= link_to "Thiết lập tài khoản", edit_path, class: 'main_menu_second' %></li>
              <li class="second_list second_list_border"><%= link_to "Đăng xuất", signout_path, class: 'main_menu_second', id: "id_signout" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div> <!-- END #main_menu -->
  </div> <!-- END .container -->
</div> <!-- END #header -->

app/views/layouts/_header_maps.html.erb
<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Nunc tincidunt</a></li>
    <li><a href="#tabs-2">Proin dolor</a></li>
  </ul>
  <div id="tabs-1">
  </div>

  <div id="tabs-2">
    <div id="map-canvas"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/google_bus.html.erb
<meta charset="utf-8" />
<title><%= full_title(yield(:title)) %></title>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <script>
    $(function() {
      $( "#tabs" ).tabs({
        event: "mouseover"
      });
    });
  </script>
</head>

<style>
  #map-canvas {
    height: 81%;
    margin: -16.7px;
    padding: 60px
  }
</style>

  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqAmcqQTrwsmAIpTcqMQQIeA9v85YrQOU&sensor=true">
  </script>
  <script>
    google.maps.visualRefresh = true;
    var map;
    function initialize() {
      var mapOptions = {
        zoom: 18,
        center: new google.maps.LatLng(10.7714015, 106.70627820000004),
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
  </script>

<body>
  <div id="tabs">
    <ul>
      <li><a href="#tabs-1">Tìm Tuyến Xe Buýt</a></li>
      <li><a href="#tabs-2">Tìm Tuyến Đi Ngắn Nhất</a></li>
      <li><%= link_to "Về Trang Chủ", root_path %></li>
    </ul>
    <div id="tabs-1">
      <div id="map-canvas"></div>
    </div>
    <div id="tabs-2">
      <p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc. Duis scelerisque molestie turpis. Sed fringilla, massa eget luctus malesuada, metus eros molestie lectus, ut tempus eros massa ut dolor. Aenean aliquet fringilla sem. Suspendisse sed ligula in ligula suscipit aliquam. Praesent in eros vestibulum mi adipiscing adipiscing. Morbi facilisis. Curabitur ornare consequat nunc. Aenean vel metus. Ut posuere viverra nulla. Aliquam erat volutpat. Pellentesque convallis. Maecenas feugiat, tellus pellentesque pretium posuere, felis lorem euismod felis, eu ornare leo nisi vel felis. Mauris consectetur tortor et purus.</p>
    </div>
  </div>
</body>
</html>

app/views/layouts/google_map.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Google Map</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      html, body, #map-canvas {
        height: 60%;
        width: 60%;
        margin: 10px;
        padding: 60px
      }
    </style>

    <script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqAmcqQTrwsmAIpTcqMQQIeA9v85YrQOU&sensor=true">
</script>
<script>
  var map;
  function initialize() {
    var mapOptions = {
      zoom: 12,
      center: new google.maps.LatLng(10.7714015, 106.70627820000004),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById('map-canvas'),
        mapOptions);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>
  </head>
  <body>
    <div id="map&#45;canvas"></div>
  </body>
</html>

app/views/layouts/layout_index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>